### ISSUE TITLE
Tauri rc.3 is stopping wildcard url

### ISSUE THREAD

**Issue by windht** [windht/watcher#5]
Currently tauri is stopping apps to make wildcard call due to the new http scope config. Thus making app cannot make any external calls.

https://github.com/tauri-apps/tauri/issues/3507

And there is already an open PR handling this. Will need to update the config to match the new wildcard scope when the PR is merged 

https://github.com/tauri-apps/tauri/pull/3515

**Comment by lucasfernog** [comment]
Merged. We'll cut a new release today.
